import { IGridBoxProps } from "../../styles/common";

export const FooterTexts: IGridBoxProps[] = [
  {
    label: "제주선한병원",
    start: 2,
    size: 5,
    row: 2,
    rowsize: 1,
    fontSize: 32,
    fontWeight: 500,
  },
  {
    label: "SITE MENU",
    start: 7,
    size: 5,
    rowsize: 1,
    row: 2,
    fontSize: 32,
    fontWeight: 400,
  },
  {
    label: "제주선한병원 제주특별자치도 제주시 특별자치도 중앙로 616",
    start: 2,
    size: 5,
    row: 3,
    rowsize: 1,
    fontSize: 16,
    fontWeight: 400,
    color: "#DBE4E8",
  },
  {
    label: "이용약관",
    start: 7,
    size: 5,
    row: 3,
    rowsize: 1,
    fontSize: 16,
    fontWeight: 400,
    color: "#DBE4E8",
  },
  {
    label: `대표자 : \n사업자등록번호 : \n전화 : 02-0000-0000\n팩스 : 02-0000-0000\n이메일 : `,
    start: 2,
    size: 5,
    row: 4,
    rowsize: 2,
    fontSize: 16,
    fontWeight: 400,
    color: "#DBE4E8",
  },
  {
    label: "개인정보처리방침",
    row: 4,
    rowsize: 2,
    start: 7,
    size: 5,
    fontSize: 16,
    color: "#DBE4E8",
    fontWeight: 400,
  },
  {
    label: "© 2024 제주선한병원. All rights reserved.",
    row: 6,
    rowsize: 1,
    start: 7,
    size: 5,
    color: "#DBE4E8",
    fontSize: 16,
    fontWeight: 400,
  },
];
